### ISSUE TITLE
Conversion from Jasmine

### ISSUE THREAD

**Issue by doug-wade** [jamestalmage/ava-codemods#22]
We use jasmine extensively here at [Redfin](https://github.com/redfin), and we're starting the long and tedious process of migrating to ava to simplify our babelification / es6, and to get our tests to run faster.  It would significantly speed up our migration if we could use a codemod.

**Comment by jamestalmage** [comment]
Take a look at the `mocha` branch (not yet merged).

It should handle the basic `describe` / `it` conversion. Happy to take PR's focused on Jasmine (don't worry about any CLI integration just yet).

Beware if you are doing something like this:

``` js
describe('foo', function () {
  var x;
  var y;
  beforeEach(function () {
    x = someFixture();
    y = otherFixture();
  });

  it('testA', ...);
  it('testB', ...);
});
```

You are going to need to change how you do things to take advantage of AVA's async nature. `testA` and `testB` will run concurrently, so accessing the shared variable is likely to cause problems. You don't have this problem in `mocha`, because both tests are never active together.

You could just default to `test.serial`, but then you miss out on async execution.

You could transition all of them to using context:

``` js
test.beforeEach(t => {
  t.context = {
    x: someFixture(),
    y: someOtherFixture()
  };
});

test('testA', t => {
  let {x, y} = t.context;
  // use x and y as you did before
});

test('testB', t => {
  let {x, y} = t.context;
  // use x and y as you did before
});
```

Or you could just use setup functions as recommended in the AVA recipes:

``` js
const setup = () =>  {
  x: someFixture(),
  y: someOtherFixture()
};

test('testA', t => {
  let {x, y} = setup();
  // use x and y as you did before
});

test('testB', t => {
  let {x, y} = setup();
  // use x and y as you did before
});
```

Neither of these help you if `someFixture()` or `someOtherFixture()` rely on global state. In that case, you probably are stuck with `test.serial` (or transitioning away from using global state in your app - which is better if doable).

All the above is what makes these codemods difficult, and why we haven't made a ton of progress yet.
